# Generated by Django 2.2.2 on 2019-06-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=35)),
                ('condition', models.TextField()),
                ('cause', models.TextField()),
                ('criteria', models.TextField()),
                ('effect', models.TextField()),
                ('recommendation', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='new', max_length=35)),
            ],
            options={
                'ordering': ('-status',),
            },
        ),
    ]
