# Generated by Django 2.2.2 on 2019-06-14 18:07

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import resolve_findings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Grantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cfda', models.IntegerField(validators=[resolve_findings.models.validate_cfda_number])),
                ('recipient', models.ManyToManyField(to='resolve_findings.Grantee')),
            ],
            options={
                'ordering': ('cfda',),
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=35)),
                ('condition', models.TextField()),
                ('cause', models.TextField()),
                ('criteria', models.TextField()),
                ('effect', models.TextField()),
                ('recommendation', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='new', max_length=35)),
                ('agencies_affected', models.ManyToManyField(to='resolve_findings.Agency')),
                ('grantee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='resolve_findings.Grantee')),
            ],
            options={
                'ordering': ('-status',),
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='grantees',
            field=models.ManyToManyField(to='resolve_findings.Grantee'),
        ),
    ]
