# Generated by Django 2.2.2 on 2019-06-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_findings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='finding_type',
            field=models.CharField(choices=[('material_weakness', 'Material Weakness'), ('significant_deficiency', 'Significant Deficiency')], default='material_weakness', max_length=100),
        ),
    ]
