# Generated by Django 2.2.2 on 2019-06-13 22:38

from django.db import migrations, models
import django.db.models.deletion
import resolve_findings.models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_findings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cfda', models.IntegerField(validators=[resolve_findings.models.validate_cfda_number])),
                ('recipient', models.ManyToManyField(to='resolve_findings.Grantee')),
            ],
            options={
                'ordering': ('cfda',),
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('grantees', models.ManyToManyField(to='resolve_findings.Grantee')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='agencies_affected',
            field=models.ManyToManyField(to='resolve_findings.Agency'),
        ),
        migrations.AddField(
            model_name='finding',
            name='grantee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='resolve_findings.Grantee'),
        ),
    ]
