# Generated by Django 2.2.2 on 2019-06-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_findings', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='published',
            new_name='is_published',
        ),
    ]
